name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage-badge

      - name: Run tests with coverage
        env:
          API_KEY: DUMMY
        run: |
          pytest -q --cov=strategy --cov-report=term-missing --cov-report=xml

      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Commit badge if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update coverage badge [skip ci]"
          file_pattern: coverage.svg